{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "98862173",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.metrics import accuracy_score, r2_score\n",
    "\n",
    "from sklearn.linear_model import LinearRegression, LogisticRegression\n",
    "from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor\n",
    "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor\n",
    "\n",
    "st.set_page_config(page_title=\"Supervised Learning Project\", layout=\"wide\")\n",
    "\n",
    "st.title(\"📊 Supervised Learning Project\")\n",
    "st.write(\"Upload dataset, train model, and make predictions.\")\n",
    "\n",
    "# Upload CSV\n",
    "uploaded_file = st.file_uploader(\"Upload CSV File\", type=[\"csv\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "\n",
    "    df = pd.read_csv(uploaded_file)\n",
    "\n",
    "    st.subheader(\"Dataset Preview\")\n",
    "    st.dataframe(df.head())\n",
    "\n",
    "    st.subheader(\"Dataset Information\")\n",
    "    st.write(\"Rows:\", df.shape[0])\n",
    "    st.write(\"Columns:\", df.shape[1])\n",
    "\n",
    "    columns = df.columns.tolist()\n",
    "\n",
    "    target = st.selectbox(\"Select Target Column\", columns)\n",
    "\n",
    "    features = st.multiselect(\n",
    "        \"Select Feature Columns\",\n",
    "        [col for col in columns if col != target],\n",
    "        default=[col for col in columns if col != target]\n",
    "    )\n",
    "\n",
    "    if len(features) > 0:\n",
    "\n",
    "        X = df[features]\n",
    "        y = df[target]\n",
    "\n",
    "        # Handle categorical columns\n",
    "        le_dict = {}\n",
    "\n",
    "        for col in X.columns:\n",
    "            if X[col].dtype == \"object\":\n",
    "                le = LabelEncoder()\n",
    "                X[col] = le.fit_transform(X[col].astype(str))\n",
    "                le_dict[col] = le\n",
    "\n",
    "        if y.dtype == \"object\":\n",
    "            target_encoder = LabelEncoder()\n",
    "            y = target_encoder.fit_transform(y)\n",
    "\n",
    "        task_type = st.radio(\n",
    "            \"Select Problem Type\",\n",
    "            [\"Classification\", \"Regression\"]\n",
    "        )\n",
    "\n",
    "        if task_type == \"Classification\":\n",
    "            model_name = st.selectbox(\n",
    "                \"Choose Model\",\n",
    "                [\n",
    "                    \"Logistic Regression\",\n",
    "                    \"Decision Tree\",\n",
    "                    \"Random Forest\"\n",
    "                ]\n",
    "            )\n",
    "        else:\n",
    "            model_name = st.selectbox(\n",
    "                \"Choose Model\",\n",
    "                [\n",
    "                    \"Linear Regression\",\n",
    "                    \"Decision Tree\",\n",
    "                    \"Random Forest\"\n",
    "                ]\n",
    "            )\n",
    "\n",
    "        test_size = st.slider(\n",
    "            \"Test Size\",\n",
    "            0.1,\n",
    "            0.4,\n",
    "            0.2\n",
    "        )\n",
    "\n",
    "        if st.button(\"Train Model\"):\n",
    "\n",
    "            X_train, X_test, y_train, y_test = train_test_split(\n",
    "                X,\n",
    "                y,\n",
    "                test_size=test_size,\n",
    "                random_state=42\n",
    "            )\n",
    "\n",
    "            # Classification Models\n",
    "            if task_type == \"Classification\":\n",
    "\n",
    "                if model_name == \"Logistic Regression\":\n",
    "                    model = LogisticRegression(max_iter=1000)\n",
    "\n",
    "                elif model_name == \"Decision Tree\":\n",
    "                    model = DecisionTreeClassifier(random_state=42)\n",
    "\n",
    "                else:\n",
    "                    model = RandomForestClassifier(\n",
    "                        n_estimators=100,\n",
    "                        random_state=42\n",
    "                    )\n",
    "\n",
    "            # Regression Models\n",
    "            else:\n",
    "\n",
    "                if model_name == \"Linear Regression\":\n",
    "                    model = LinearRegression()\n",
    "\n",
    "                elif model_name == \"Decision Tree\":\n",
    "                    model = DecisionTreeRegressor(random_state=42)\n",
    "\n",
    "                else:\n",
    "                    model = RandomForestRegressor(\n",
    "                        n_estimators=100,\n",
    "                        random_state=42\n",
    "                    )\n",
    "\n",
    "            model.fit(X_train, y_train)\n",
    "\n",
    "            predictions = model.predict(X_test)\n",
    "\n",
    "            st.subheader(\"Model Performance\")\n",
    "\n",
    "            if task_type == \"Classification\":\n",
    "                score = accuracy_score(y_test, predictions)\n",
    "                st.success(f\"Accuracy: {score:.4f}\")\n",
    "\n",
    "            else:\n",
    "                score = r2_score(y_test, predictions)\n",
    "                st.success(f\"R² Score: {score:.4f}\")\n",
    "\n",
    "            st.subheader(\"Prediction Results\")\n",
    "\n",
    "            result_df = pd.DataFrame({\n",
    "                \"Actual\": y_test,\n",
    "                \"Predicted\": predictions\n",
    "            })\n",
    "\n",
    "            st.dataframe(result_df.head(20))\n",
    "\n",
    "            csv = result_df.to_csv(index=False)\n",
    "\n",
    "            st.download_button(\n",
    "                \"Download Predictions\",\n",
    "                csv,\n",
    "                file_name=\"predictions.csv\",\n",
    "                mime=\"text/csv\"\n",
    "            )\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
